add_newline = false

format = '|\[$username@$hostname $directory\]| $character '

[username]
format = "[$user]($style)"
show_always = true
style_user="green"
style_root="white"
[hostname]
ssh_only = false
format = "[$hostname]($style)"
style="cyan"

[directory]
format = '[$path]($style)'
style = 'red'
[character]
format = "$symbol"
success_symbol = '\$'
error_symbol = '\$'
